### ISSUE TITLE
Way to use terminal colors

### ISSUE THREAD

**Issue by ThatOneCalculator** [lemnos/tt#8]
I get that there are a lot of fancy themes, but is there a way just to use my terminal colors?

**Comment by lemnos** [comment]
Sorry for the prolonged response. I just added `-notheme`. Bear in mind that some terminal themes choose odd base colors and may not work particularly well with the options. I've also added `-bold` in the event that a terminal's white color is not clearly distinguishable from its foreground color.

**Comment by ThatOneCalculator** [comment]
Awesome, thanks
